default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [text]
      - id: end-of-file-fixer
        types: [text]
      - id: check-yaml
        types: [yaml]
      - id: check-toml
        types: [toml]
      - id: check-merge-conflict
        types: [text]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix]
        types: [python]
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        types: [python]
        additional_dependencies: [types-setuptools]
